platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'ATC' do
  pod "ESTabBarController-swift"
  pod "TPKeyboardAvoiding"
  pod "AFNetworking"
  pod "KSToastView"
  pod "MBProgressHUD"
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'SlideMenuControllerSwift'
  pod 'pop'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
